from telebot.handler_backends import State, StatesGroup  # States

#For admin's dashboard
class Panel(StatesGroup):
    open_admin_st = State()
    send_rassilka_st = State()
    confirm_rasilka_st = State()
    categories_and_products_st = State()
    categories_func_st = State()
    add_categories_st = State()
    add_categories_ru = State()
    delete_categories_st = State()
    ask_delete_categories_st = State()
    change_categories_st = State()
    change_categories_lang_st = State()
    ask_new_name_st = State()
    products_admin_st = State()
    ask_delete_products_st = State()
    delete_products_st = State()
    products_add_admin_st = State()
    add_product_name_st = State()
    add_product_name_ru_st = State()
    add_price_product_st = State()
    add_image_product_st = State()
    change_products_st = State()
    choose_lange_change_product = State()
    choose_edit_btn_st = State()
    price_choose_edit_btn_st = State()
    price_image_edit_btn = State()
    change_name_product_st = State()
    statistica_st = State()
    products_statistika_st = State()
    get_end_time_statistics_st = State()
    get_one_filter_product_date_st = State()
    branch_statistics_st = State()
    get_end_time_branch_st = State()
    get_one_filter_branch_date_st = State()
    average_count_st = State()
    get_start_avaerage_count_st = State()
    get_one_average_sum_st = State()
#For user's dashboard
class MyStates(StatesGroup):
    headers_st = State()
    contacts_st = State()
    settings_st = State()
    change_language_st = State()
    complaint_branch_st = State()
    get_answer  = State()
    order_func_st = State()
    pickup_func_st = State()
    menu_func_st = State()
    products_menu_st = State()
    basket_user_st = State()
    none_st  =State()
    enter_number_by_handle_st = State()
    confirm_order_st =State()
    comments_st = State()
    payment_type_st = State()
    confirm_last_st =State()
    delivery_func_st = State()
    deliveryss_branch_func_st = State()
    not_home_handle_st = State()
    not_home_st = State()
    confirm_location_st = State()
    delivery_address_two_st = State()
    my_addresses_func_st = State()
    click_payment_st = State()
#For user's registration
class Register(StatesGroup):
    lang_st = State()
    full_name_st = State()